### ISSUE TITLE
Locale request: ru-KZ

### ISSUE THREAD

**Issue by yenbekbay** [sanity-io/locales#108]
**Which locale do you wish to add?**
First check if your locale has already been requested. If so, go and add an emoji to that request to show your support.

For new requests, write the locale identifier in the subject after the colon.

Example: "**Locale request: nb-NO**".

We use BCP-47 with region subtags, [see "IETF language tag"](https://en.wikipedia.org/wiki/IETF_language_tag).

**Maintainer**
Sanity will bootstrap and keep the locale updated using AI. We would like human contributors to help maintain the locales by improving them and/or reviewing pull requests from the AI and from other contributors as they come in. Check the box below if you want to be added as a maintainer of this locale. As a maintainer you will be automatically added as reviewer to future PRs that improve it.

If you are not the author of this issue, but would still like to be added as a maintainer, please add a comment to the thread.

- [x] I want to be added as maintainer

**Comment by runeb** [comment]
Hello @yenbekbay , thank you for your request. I have added an autogenerated locale plugin for `ru-KZ` in PR https://github.com/sanity-io/locales/pull/110. Could you please help review it?
