### ISSUE TITLE
Locale request: uk-UA

### ISSUE THREAD

**Issue by fomazov** [sanity-io/locales#209]
Hey, I would like ask you to generate default localization data for Ukrainian language.

Since I am a native speaker, I can review PR and adjust the translation where needed.

Also, I've been meaning to explore the Studio in depth for a long time, so I'll kill two birds with one stone, will explore the project and help the community.

Thank you in advance,
Oleksii

- [X] I want to be added as maintainer

**Comment by runeb** [comment]
Thank you for your request, @fomazov ! I have added an initial AI translation in #213
