### ISSUE TITLE
Locale request: he-IL

### ISSUE THREAD

**Issue by galnir** [sanity-io/locales#226]
Is it possible to add Hebrew? Does it also require some adjustments to the Rich Text Editor since its an RTL language?

- [x] I want to be added as maintainer

**Comment by runeb** [comment]
Hello @galnir, thank you for your feature request addition! Unfortunately we cannot currently support RTL languages, but I have added more signal for `he-IL` in the event we support in the future! See also #189.

**Comment by galnir** [comment]
> Hello @galnir, thank you for your feature request addition! Unfortunately we cannot currently support RTL languages, but I have added more signal for `he-IL` in the event we support in the future! See also #189.

Is there a way to translate the Studio without a package? dir="rtl" on the Studio looks ok for me and I'd like to be able to translate some stuff
