### ISSUE TITLE
Maintainer: th-TH

### ISSUE THREAD

**Issue by CcNicebruh** [sanity-io/locales#229]
I know this language and would like to help improve it by being added as a maintainer. As a maintainer I will be automatically added as a reviewer to pull requests from AI and other contributors.

**Comment by runeb** [comment]
Thank you @CcNicebruh! I will add you to the maintainer list, please have a look at the CONTRIBUTING.md file for practical information. You may also join #locales-contributors on https://slack.sanity.io/
