### ISSUE TITLE
Maintainer: pt-PT

### ISSUE THREAD

**Issue by jrparente** [sanity-io/locales#239]
I know this language and would like to help improve it by being added as a maintainer. As a maintainer I will be automatically added as a reviewer to pull requests from AI and other contributors.

**Comment by rexxars** [comment]
Thank you @jrparente ! I will add you to the maintainer list, please have a look at the [CONTRIBUTING.md](https://github.com/sanity-io/locales/blob/main/CONTRIBUTING.md) file for practical information. You may also join #locales-contributors on https://slack.sanity.io/
