### ISSUE TITLE
fix(fr-FR): automated translation updates

### ISSUE THREAD

**Issue by thierryteyssier** [sanity-io/locales#271]
https://github.com/sanity-io/locales/blob/1cc4c60bc1bc8a81362022d88bea36c960dc122c/locales/fr-FR/src/vision.ts#L66

Les perspectives vous permettent d'exécuter vos requêtes à partir d'une autre "vue" des documents de votre ensemble de données.

**Comment by runeb** [comment]
Thanks @thierryteyssier ! Could you see if the guide in CONTRIBUTING.md in the repo is helpful for how to add a suggestion? You could open a PR with your change, or add suggestions to already open PRs
