### ISSUE TITLE
Maintainer: pt-BR

### ISSUE THREAD

**Issue by fernandolucchesi** [sanity-io/locales#272]
I know this language and would like to help improve it by being added as a maintainer. As a maintainer I will be automatically added as a reviewer to pull requests from AI and other contributors.

**Comment by runeb** [comment]
Thank you @fernandolucchesi! I will add you as soon as we merge the pending PRs

**Comment by rexxars** [comment]
Hi Fernando, nice to see you here - glad you're helping out 👋

Added you as maintainer in 4bd81c843547838cc24ed2788403f625756c5975, please have a look at the [CONTRIBUTING.md](https://github.com/sanity-io/locales/blob/main/CONTRIBUTING.md) file for practical information. You may also join #locales-contributors on https://slack.sanity.io/ 🙂
