### ISSUE TITLE
Inconsistent translation of "Upload" (fr-FR)

### ISSUE THREAD

**Issue by AymericWilke** [sanity-io/locales#298]
In the context of the actions menu, the "Upload" action is translated as "Téléverser":
```
'inputs.files.common.actions-menu.upload.label': 'Téléverser',
```
But everywhere else, "Upload" is translated as "Télécharger" (there's about 60 occurrences of it).

This should be fixed one way or another to keep consistency in the UI.

I would personally use "Télécharger" everywhere. What do you think @thierryteyssier, @ahelliet?

**Comment by ahelliet** [comment]
I agree for "Télécharger"

**Comment by thierryteyssier** [comment]
Same thing, agree for "Télécharger"

**Comment by AymericWilke** [comment]
![Capture d’écran 2024-01-18 à 18 46 39](https://github.com/sanity-io/locales/assets/13614273/4f3c3bcf-dd11-42dd-945e-dd3d0ad74375)

Umm… actually, thinking about it a bit more, if we put "Télécharger", there's going to be two options named the same thing but with a different purpose, which is probably worse UX.
Maybe "Charger" would do the trick? And changing all 60 occurrences of "Upload" maybe?

**Comment by ahelliet** [comment]
@thierryteyssier Sorry miss your question, maybe 'transférer' but i'm not sure if it's already used or not

**Comment by rexxars** [comment]
Closing this - feel free to open a pull request if you want this changed :)
