### ISSUE TITLE
Locale request: da-DK

### ISSUE THREAD

**Issue by Kasper-Buchholtz** [sanity-io/locales#356]
**Which locale do you wish to add?**
First check if your locale has already been requested. If so, go and add an emoji to that request to show your support.

For new requests, write the locale identifier in the subject after the colon.

Example: "**Locale request: nb-NO**".

We use BCP-47 with region subtags, [see "IETF language tag"](https://en.wikipedia.org/wiki/IETF_language_tag).

**Maintainer**
Sanity will bootstrap and keep the locale updated using AI. We would like human contributors to help maintain the locales by improving them and/or reviewing pull requests from the AI and from other contributors as they come in. Check the box below if you want to be added as a maintainer of this locale. As a maintainer you will be automatically added as reviewer to future PRs that improve it.

If you are not the author of this issue, but would still like to be added as a maintainer, please add a comment to the thread.

- [x] I want to be added as maintainer

**Comment by rexxars** [comment]
Happy to support a Danish language pack, but we'll need someone to step us as a maintainer first - let us know if you're interested by commenting here!

**Comment by Kasper-Buchholtz** [comment]
@rexxars Im very interested

**Comment by Kastholm** [comment]
@rexxars @Kasper-Buchholtz   I'm also very interested in a Danish language pack, would be awesome if we could make it happen.
in case you need help with translating, im ready to help.

**Comment by rexxars** [comment]
Please have a look at #463 for the initial AI-generated translation!

**Comment by rexxars** [comment]
[@sanity/locale-da-dk@v1.0.1](https://www.npmjs.com/package/@sanity/locale-da-dk) has the first automated translations
