### ISSUE TITLE
Maintainer: ja-JP

### ISSUE THREAD

**Issue by rikusen0335** [sanity-io/locales#481]
I know this language and would like to help improve it by being added as a maintainer. As a maintainer I will be automatically added as a reviewer to pull requests from AI and other contributors.

**Comment by rikusen0335** [comment]
I'm gonna open PR for some fixes

**Comment by rexxars** [comment]
Thank you! Added you as maintainer, please have a look at the [CONTRIBUTING.md](https://github.com/sanity-io/locales/blob/main/CONTRIBUTING.md) file for practical information. You may also join #locales-contributors on https://slack.sanity.io/  :)
